# -*- coding: utf-8 -*-
"""Ksawyouipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rCbT8EIx5AGFJmjXQw_WUjkwIxi5jbxu
"""

from flask import Flask, request, jsonify
import logging
from sklearn.linear_model import LinearRegression
import numpy as np

app = Flask("Ksawyou")

model = LinearRegression()

logging.basicConfig(filename='api.log', level=logging.INFO)

def train_model():

    data = request.get_json()
    X_train = np.array(data['X_train']).reshape(-1, 1)
    y_train = np.array(data['y_train'])

    model.fit(X_train, y_train)

    logging.info("Model training completed.")

def predict(data):
  """Import the data that you want """
    data = request.get_json()
    X_test = np.array(data['X_test']).reshape(-1, 1)

    predictions = model.predict(X_test)
    prediction = {"prediction": "Your prediction here"}
    logging.info("Model prediction made.")
    return prediction

@app.route('/train', methods=['POST'])
def train():
    train_model()
    return jsonify({"message": "Model trained successfully."})

@app.route('/predict', methods=['POST'])
def predict():
    data = request.get_json()
    prediction = predict_model(data)
    return jsonify(prediction)

@app.route('/logfile', methods=['GET'])
def get_logfile():
    with open('api.log', 'r') as logfile:
        logs = logfile.read()
    return logs

if __name__ == '__main__':
    app.run(debug=True)